#pragma once

#define DDRAW_FEATURE_DEFAULT 0

#define ENABLE_FIX_NO_DIRECTPLAY 1
#define ENABLE_FIX_DEP_STARTUP_CRASH 1
#define ENABLE_FIX_FAKE_VRAM_POLL 1
#define ENABLE_FIX_USER_FILES_PATH 1
#define ENABLE_FIX_IMG_NO_BUFFERING 1
#define ENABLE_FIX_UNNAMED_CDSTREAM_SEMAPHORE 1
#define ENABLE_ENHANCEMENT_DEFAULT_DESKTOP_RESOLUTION 1
#define ENABLE_ENHANCEMENT_NO_CENSORSHIP 1
#define ENABLE_ENHANCEMENT_WINDOWED_MODE 1
#define ENABLE_ENHANCEMENT_SKIP_INTRO_SPLASHES 1
