#pragma once

#if defined(SILENTPATCH_SPEEDRUN)
#include "config_speedrun.h"
#else
#include "config_all_fixes.h"
#endif

#ifndef DDRAW_FEATURE_DEFAULT
#define DDRAW_FEATURE_DEFAULT 1
#endif

#ifndef ENABLE_FIX_NO_DIRECTPLAY
#define ENABLE_FIX_NO_DIRECTPLAY DDRAW_FEATURE_DEFAULT
#endif
#ifndef ENABLE_FIX_DEP_STARTUP_CRASH
#define ENABLE_FIX_DEP_STARTUP_CRASH DDRAW_FEATURE_DEFAULT
#endif
#ifndef ENABLE_FIX_FAKE_VRAM_POLL
#define ENABLE_FIX_FAKE_VRAM_POLL DDRAW_FEATURE_DEFAULT
#endif
#ifndef ENABLE_FIX_USER_FILES_PATH
#define ENABLE_FIX_USER_FILES_PATH DDRAW_FEATURE_DEFAULT
#endif
#ifndef ENABLE_FIX_IMG_NO_BUFFERING
#define ENABLE_FIX_IMG_NO_BUFFERING DDRAW_FEATURE_DEFAULT
#endif
#ifndef ENABLE_FIX_UNNAMED_CDSTREAM_SEMAPHORE
#define ENABLE_FIX_UNNAMED_CDSTREAM_SEMAPHORE DDRAW_FEATURE_DEFAULT
#endif
#ifndef ENABLE_ENHANCEMENT_DEFAULT_DESKTOP_RESOLUTION
#define ENABLE_ENHANCEMENT_DEFAULT_DESKTOP_RESOLUTION DDRAW_FEATURE_DEFAULT
#endif
#ifndef ENABLE_ENHANCEMENT_NO_CENSORSHIP
#define ENABLE_ENHANCEMENT_NO_CENSORSHIP DDRAW_FEATURE_DEFAULT
#endif
#ifndef ENABLE_ENHANCEMENT_WINDOWED_MODE
#define ENABLE_ENHANCEMENT_WINDOWED_MODE DDRAW_FEATURE_DEFAULT
#endif
