[SilentPatch]
; Allows to override units used by the game - 0 forces metric units, 1 forces imperial units,
; -1 makes the game use units based on system locale
Units=-1
; Use the desktop refresh rate instead of a forced 60Hz while in fullscreen mode. This will get rid of
; a flicker when starting the game on a high refresh rate display.
UseDesktopRefreshRate=1
; Runs the game in a desktop window instead of fullscreen.
WindowedMode=0